---
- name: Install tools, necessary for compiling crosstool-ng
  apt:
    name: ['gperf', 'bison', 'flex', 'texinfo', 'help2man', 'gawk', 'libncurses5-dev', 'make', 'python-dev', 'dh-autoreconf', 'libtool-bin']
    state: present
  become: true

- name: Copy rpi toolchain configuration file
  template:
    src: arm-rpi-linux-gnueabihf.config
    dest: /usr/local/etc/arm-rpi-linux-gnueabihf.config
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy rpi toolchain build script
  template:
    src: build-rpi-toolchain.sh
    dest: /usr/local/bin/build-rpi-toolchain.sh
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy the rpi cmake toolchain file
  template:
    src: toolchain-rpi.cmake
    dest: /usr/local/etc/toolchain-rpi.cmake
    owner: root
    group: root
    mode: 0644
  become: true
